### ISSUE TITLE
MP4 video is displayed "inline" even though the mp4 extension is not in the "inline downloads" conf

### ISSUE THREAD

**Issue by Gui13** [filegator/filegator#153]
**Describe the bug**

When I click on an mp4 video, it is displayed "inline" as a text, which shows garbarge

**To Reproduce**

1. Put mp4 in your data folder
2. Click on it in the filegator UI
3. see garbage in the preview interface

**Expected behavior**

Either a download is triggered or the browser embeds a video and plays it

**Screenshots**

![image](https://user-images.githubusercontent.com/44523/97780068-a6055d80-1b82-11eb-89f1-8fc40a0361a3.png)

**Logs**

None seem relevant

My conf has ` 'download_inline' => ['pdf'], // download inline in the browser, array of extensions, use * for all`

**Environment (please complete the following information):**
 - FileGator Version 7.4.5
 - Server: php:apache docker image
 - PHP Version:  php:apache docker image (last php 7 I expect?)
 - Browser Firefox

**Additional context**

**Comment by Gui13** [comment]
I'm investigating whether I might be missing the fileinfo php module.

**Comment by Gui13** [comment]
Installing the php fileinfo doesn't solve the problem

**Comment by alcalbg** [comment]
Hi,

Unfortunately I am not able to reproduce this. I've tried with this [mp4 file](https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4) and everything works as expected.

My env:
- FileGator Version 7.4.5 (default installation and configuration)
- Server: debian 10.6
- PHP Version:  7.3.19-1~deb10u1
- Browser Chrome, Firefox, Safari

Is anyone else getting this?

**Comment by Gui13** [comment]
Hello @alcalbg ,

Thank you for trying to reproduce. I'm using now docker image 7.3-apache which is based in debian Buster.
I still have the issue, but I don't know why.

I suspect that this is an issue of mime type resolution, although issuing `file <my mp4>` in the container seems to return the correct mime type:

```
root@0e057d2f24ac:/data# file xxx-2020-10-29.mp4
xxx-2020-10-29.mp4: ISO Media, MP4 Base Media v1 [IS0 14496-12:2003]
```

This is my docker-compose setup:

```yaml
version: "2"

services:
  videos:
    image: chialab/php:7.4-apache
    restart: always
    volumes:
      - ./filegator/:/var/www/html:rw
      - ./configuration.php:/var/www/html/filegator/configuration.php:ro
      - /data/vids:/data:ro
      - logs:/private/logs:rw
    networks:
      - web
    labels:
      - "traefik.backend=my-vids"
      - "traefik.docker.network=web"
      - "traefik.eggalert.frontend.rule=Host:xxx.yyy"
      - "traefik.enable=true"

networks:
  web:
    external: true

volumes:
  logs:
```

Extracts of the configuration.php:

```php
    'public_path' => APP_PUBLIC_PATH,
    'public_dir' => APP_PUBLIC_DIR,
    'overwrite_on_upload' => false,
    'timezone' => 'Europe/Brussels', // https://www.php.net/manual/en/timezones.php
    'download_inline' => ['pdf'], // download inline in the browser, array of extensions, use * for all

    'frontend_config' => [
        'app_name' => 'xxx',
        'app_version' => APP_VERSION,
        'language' => 'french',
        'logo' => 'https://xxx.yyy/wp-content/uploads/2019/08/cropped-logo_fondblanc-1.png',
        'upload_max_size' => 100 * 1024 * 1024, // 100MB
        'upload_chunk_size' => 1 * 1024 * 1024, // 1MB
        'upload_simultaneous' => 3,
        'default_archive_name' => 'archive.zip',
        'editable' => [],
        'date_format' => 'YY/MM/DD hh:mm:ss', // see: https://momentjs.com/docs/#/displaying/format/
        'guest_redirection' => '', // useful for external auth adapters
    ],
```

There are no useful logs in the private/logs directory (only logins from users).

Can I debug the PHP to understand what is happening?
