### ISSUE TITLE
Docker container issue: Folder not writable: /private/logs/ 

### ISSUE THREAD

**Issue by s-kaczmarek** [filegator/filegator#256]
Docker container created out of the image from your Docker file is not working properly - after accessing website, it says: 

Folder not writable: /private/logs/

**Comment by alcalbg** [comment]
cc @norweeg

**Comment by s-kaczmarek** [comment]
This is how I run this container, with docker-compose file:

```
version: '2'
services:
  filegator:
    build: .
    image: filegator:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ~/filegator/repository:/var/www/filegator/repository
      - ~/filegator/private:/var/www/filegator/private

volumes:
  repository:
  private:
```

Maybe I messed up something with it, I don't know... Should I set GID 33 in docker compose file? Could you please give me an example of docker-compose file?

**Comment by norweeg** [comment]
what are the permissions on `~/filegator/repository` and `~/filegator/private`?  Can you show me the output of `ls -l -n ~/filegator`.  I suspect it will say something like

```
drwxr-xr-x 1000 1000 private
drwxr-xr-x 1000 1000 repository
```

I think 

```
drwxrwxr-x 1000 33 private
drwxrwxr-x 1000 33 repository
```
would probably be preferable where you, outside the container (1000) and the filegator process inside the container (33) both have rwx on those directories

`chmod -R g+w ~/filegator && chown -R 1000:33 ~/filegator` should set those permissions for you

**Comment by norweeg** [comment]
what are the permissions on `~/filegator/repository` and `~/filegator/private`?  Can you show me the output of `ls -l -n ~/filegator`.  I suspect it will say something like

```
drwxr-xr-x 1000 1000 private
drwxr-xr-x 1000 1000 repository
```

I think 

```
drwxrwxr-x 1000 33 private
drwxrwxr-x 1000 33 repository
```
would probably be preferable where you (1000) and the filegator process inside the container (33) both have rwx on those directories

`chmod -R g+w ~/filegator && chown -R 1000:33 ~/filegator`  should set those permissions for you

**Comment by s-kaczmarek** [comment]
Thanks for your answer! Unfortunately, that didn't fix the issue. I still see error:

```
Folder not writable: /private/logs/ 
```

Further investigation and I've found, that this folder doesn't exist, so I decided to create it manually:

```
docker_admin@docker_test3:~/filegator$ cd private/
docker_admin@docker_test3:~/filegator/private$ ls -al
total 8
drwxrwxrwx 2 docker_admin www-data 4096 Aug 14 17:18 .
drwxrwxr-x 4 docker_admin www-data 4096 Aug 14 17:22 ..
docker_admin@docker_test3:~/filegator/private$ mkdir logs
docker_admin@docker_test3:~/filegator/private$ ls -al
total 12
drwxrwxrwx 3 docker_admin www-data     4096 Aug 23 17:46 .
drwxrwxr-x 4 docker_admin www-data     4096 Aug 14 17:22 ..
drwxrwxr-x 2 docker_admin docker_admin 4096 Aug 23 17:46 logs
```

After a webpage refresh, this error disappeared, but left me with a blank, white page (filegator's favicon is visible). I tried to change permission to /private.logs folder to 777, but that didn't work too.

```
docker_admin@docker_test3:~/filegator/private$ ls -al
total 16
drwxrwxrwx 4 docker_admin www-data     4096 Aug 23 17:47 .
drwxrwxr-x 4 docker_admin www-data     4096 Aug 14 17:22 ..
drwxrwxrwx 2 docker_admin docker_admin 4096 Aug 23 17:47 logs
drwxr-xr-x 2 www-data     www-data     4096 Aug 23 17:47 tmp
```

I've changed ownership once again as you recommended in a previous post, but still blank page.

Is my docker-compose file valid? I'm not sure about this part:

```
volumes:
  repository:
  private:
```

**Comment by s-kaczmarek** [comment]
Ok, I've created a container form image on dockerhub: https://hub.docker.com/r/kwillia/filegator_docker

My docker-compose looks like this:

```
version: '2'
services:
  filegator:
    image: kwillia/filegator_docker:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ~/filegator/repository:/var/www/filegator/repository
      - ~/filegator/private:/var/www/filegator/private
```

Web GUI works just fine, but I wonder if mapping of volumes works at all, because after adding a few files via web interface, I can't see them in the filesystem:

```
docker_admin@docker_test3:~/filegator$ ls -al
total 28
drwxrwxr-x  4 docker_admin www-data     4096 Aug 23 18:04 .
drwxr-xr-x 17 docker_admin docker_admin 4096 Aug 23 18:03 ..
-rw-rw-r--  1 docker_admin www-data     1076 Aug 14 17:17 Dockerfile
-rw-rw-r--  1 docker_admin www-data      291 Aug 14 17:22 filegator.yml
-rw-rw-r--  1 docker_admin docker_admin  258 Aug 23 18:03 filegator2.yml
drwxr-xr-x  2 root         root         4096 Aug 23 18:04 private
drwxr-xr-x  2 root         root         4096 Aug 23 18:04 repository
docker_admin@docker_test3:~/filegator$ ls -al private/
total 8
drwxr-xr-x 2 root         root     4096 Aug 23 18:04 .
drwxrwxr-x 4 docker_admin www-data 4096 Aug 23 18:04 ..
docker_admin@docker_test3:~/filegator$ ls -al repository/
total 8
drwxr-xr-x 2 root         root     4096 Aug 23 18:04 .
drwxrwxr-x 4 docker_admin www-data 4096 Aug 23 18:04 ..
```

**Comment by norweeg** [comment]
Pushing the image to dockerhub will not change anything.  Have you read up on how docker volumes work??  You appear to have created volumes, but then bind-mounted directories from your host to directories in question in your container.

Here's my docker-compose.yml

```yaml
version: '3.7'
services:
  filegator:
    ...
    volumes:
      # docker volumes mapped to directories in the running container
      - repository:/var/www/filegator/repository
      - private:/var/www/filegator/private
      # bind-mounted data directory on docker host mounted into the container
      - /data/I/recovered/on/friends/failed/drive/data:/var/www/filegator/repository/
    ...

volumes:
  repository:
  private:

```

the permissions on the data directory are `drwxrwxr-x 1 33 33 26 Jul 24 13:30 data`.  I do not need to write data from the host to this folder, so my user (UID 1000) does not own this directory.
