### ISSUE TITLE
FileGator in Truenas Scale

### ISSUE THREAD

**Issue by rjwill10** [filegator/filegator#547]
FileGator Version = Latest
Server = TrueNas scale 25.04.1

I've been trying to run Filegator on Truenas scale as a custom app. 

I can get it running, but I can't seem to get storage pass through to work. I have various ZFS pools that I'd like to pass through. I've tried passing though as a "host path" directly from Truenas, and also as an SMB share, but they don't appear in the UI. 

www-data has full access to the shares. YAML below:

````
services:
  filegator:
    environment:
      NVIDIA_VISIBLE_DEVICES: void
      TZ: Europe/London
    group_add:
      - 33
    image: filegator/filegator:latest
    network_mode: host
    platform: linux/amd64
    privileged: False
    pull_policy: missing
    restart: 'no'
    stdin_open: False
    tty: False
    volumes:
      - bind:
          create_host_path: False
          propagation: rprivate
        read_only: False
        source: /mnt/downloads
        target: /downloads
        type: bind
volumes: {}
x-notes: >+
  # iX App


  ## Security


  ### Container: [filegator]


  - Is running as unknown user

  - Is running as unknown group

  - Is running without [no-new-privileges] security option


  ## Bug Reports and Feature Requests


  If you find a bug in this app or have an idea for a new feature, please file
  an issue at

  https://github.com/truenas/apps

x-portals: []`

```
